[package]
name = "msp430fr6972"
version = "0.1.0"
authors = ["chrismolli <molliere.c@gmail.com>"]
edition = "2018"

[dependencies]
bare-metal = "0.2.0"
msp430 = "0.2.0"
vcell = "0.1.0"

[dependencies.msp430-rt]
optional = true
version = "0.1.0"

[features]
rt = ["msp430-rt/device"]
